//
//  NetWorkRequestDefine.m
//  QuDriver
//
//  Created by Zhuqing on 2017/9/21.
//  Copyright © 2017年 com.Qyueche. All rights reserved.
//

#import "NetWorkRequestDefine.h"

NSString *XQApiNameEnum(XQApiName name)
{
    switch (name) {
        case checkVersion:return @"api/login/checkapkversion";
            break;
        case fileupload:return @"/api/images/upload";
            break;
        case commonaAppconfig:return @"common/appconfig";
            break;
        case article:return @"api/Article/visit";
            break;
        case getCode:return @"api/login/identifycode";
            break;
        case getCodeTwo:return @"g=app&m=appv1&a=GetCode2";
            break;
        case changePassword:return @"g=app&m=appv1&a=ChangePwd";
            break;
        case customerregister:return @"customer/register";
            break;
        case login:return @"api/login/login";
            break;
        case loginSavephone:return @"api/login/savephone";
            break;
        case imageToken:return @"g=app&m=life&a=get_qiniu_token";
            break;
        case regist:return @"api/login/regist";
            break;
        case customerlogout:return @"customer/logout";
            break;
        case getParkList:return @"g=app&m=appv1&a=GetParkList";
            break;
        case getInformation:return @"api/my/index";
            break;
        case customerupdateInformation:return @"api/auth_api/changeavatar";
            break;
        case stopCarInfo:return @"g=app&m=appv1&a=GetHome";
            break;
        case checkPay:return @"g=app&m=appv1&a=CheckPay";
            break;
        case bindMac:return @"g=app&m=appv1&a=BindMac";
            break;
        case unbindMac:return @"g=app&m=appv1&a=UnBindMac";
            break;
        case getObdData:return @"http://apitest.18gps.net/GetDateServices.asmx/GetDate";
            break;
        case macReLogin:return @"g=app&m=appv1&a=MacReLogin";
            break;
        case getRailList:return @"g=app&m=appv1&a=GetRailList";
            break;
        case deleteRail:return @"g=app&m=appv1&a=DeleteRail";
            break;
        case updateRail:return @"g=app&m=appv1&a=UpdateRail";
            break;
        case addRail:return @"g=app&m=appv1&a=AddRail";
            break;
        case alarmList:return @"g=app&m=appv1&a=Alarm_List";
            break;
        case alarmDetalis:return @"g=app&m=appv1&a=Alarm_Details";
            break;
        case getHomeIcon:return @"api/index/get_index";
            break;
        case getClassify:return @"api/store/get_category_recommend";
            break;
        case getClassbanner:return @"api/store/get_category_recommend";
            break;
        case phoneNote:return @"g=app&m=telephone&a=telephone_note";
            break;
        case phonecheck:return @"g=app&m=telephone&a=checkphone";
            break;
        case phoneMakeorder:return @"g=app&m=telephone&a=makeorder";
            break;
        case phoneGoodspay:return @"g=app&m=telephone&a=goodspay";
            break;
        case phoneUpdateorder:return @"g=app&m=telephone&a=updateorder";
            break;
        case phoneSelectuserdata:return @"g=app&m=telephone&a=selectuserdata";
            break;
        case mainGoodsList:return @"api/store/get_best_product_list";
            break;
        case goodsSearch:return @"api/auth_api/get_product_list";
            break;
        case mainGoodsDetalis:return @"api/store/detail";
            break;
        case killGoodsDetalis:return @"api/store/seckill_detail";
            break;
        case mainGoodsPalceOrder:return @"api/auth_api/now_buy";
            break;
        case create_order:return @"api/auth_api/create_order";
            break;
        case addshopingCar:return @"api/auth_api/set_cart";
            break;
        case shoppingCarEditor:return @"api/auth_api/change_cart_num";
            break;
        case shoppingCarDelete:return @"api/auth_api/remove_cart";
            break;
        case confirm_order:return @"api/store/confirm_order";
            break;
        case pay_order:return @"api/auth_api/pay_order";
            break;
        case shoppingCarNum:return @"api/auth_api/get_cart_num";
            break;
        case shoppingCarGoodsList:return @"api/auth_api/get_cart_list";
            break;
        case goodsPay:return @"g=app&m=appv1&a=goodsPay";
            break;
        case orderList:return @"api/auth_api/get_user_order_list";
            break;
        case orderNum:return @"g=app&m=appv1&a=GetOrderNO";
            break;
        case orderDetalis:return @"api/my/order";
            break;
        case cancelOrder:return @"api/auth_api/apply_order_refund";
            break;
        case confirmTaked:return @"g=app&m=appv1&a=ConfirmTaked";
            break;
        case aRefundOrder:return @"api/auth_api/apply_order_refund";
            break;
        case expressInfo:return @"api/my/express";
            break;
        case mycarList:return @"g=app&m=appv1&a=GetAllCar";
            break;
        case deleteMycar:return @"g=app&m=appv1&a=DeleteCar";
            break;
        case addMyCar:return @"g=app&m=appv1&a=EditCar";
            break;
        case carParkList:return @"g=app&m=appv1&a=GetCarParkList";
            break;
        case addressList:return @"api/my/address";
            break;
        case deleteAddress:return @"api/auth_api/remove_user_address";
            break ;
        case lifeCitysList:return @"g=app&m=life&a=get_city";
            break;
        case addAddress:return @"api/auth_api/edit_user_address";
            break;
        case editAddress:return @"api/auth_api/edit_user_address";
            break;
        case defaddress:return @"api/auth_api/user_default_address";
            break;
        case lifeGetCompany:return @"g=app&m=life&a=get_company";
            break;
        case lifeSet_product_user:return @"g=app&m=life&a=set_product_user";
            break;
        case lifeGet_product_user:return @"g=app&m=life&a=get_product_user";
            break;
        case lifeSet_del_bin:return @"g=app&m=life&a=set_del_bin";
            break;
        case lifeQuery_arrearage:return @"g=app&m=life&a=query_arrearage";
            break;
        case lifeGet_money:return @"g=app&m=life&a=get_money";
            break;
        case lifeCreate_order:return @"g=app&m=life&a=create_order";
            break;
        case lifeGoodsPay:return @"g=app&m=life&a=goodsPay";
            break;
        case lifeRecord_order:return @"g=app&m=life&a=record_order";
            break;
        case myUser_pro:return @"api/my/user_pro";
            break;
        case myguide:return @"api/my/guide";
            break;
        case mybalance_list:return @"api/auth_api/user_balance_list";
            break;
        case myintegral_list:return @"api/auth_api/user_integral_list";
            break;
        case myPread_list:return @"api/my/myshopuser";
            break;
        case mymessageList:return @"api/auth_api/get_notice_list";
            break;
        case mycollect_product:return @"api/auth_api/get_user_collect_product";
            break;
        case mycoupon:return @"api/my/coupon";
            break;
        case myWithdral:return @"api/auth_api/user_extract";
            break;
        case myWithdralInfo:return @"api/my/extract";
            break;
        case get_use_coupon:return @"api/auth_api/get_use_coupon";
            break;
        case collect_product:return @"api/auth_api/collect_product";
            break;
        case cancel_product:return @"api/auth_api/uncollect_product";
            break;
        case delete_product:return @"api/auth_api/remove_user_collect_product";
            break;
        case evaluationInfo:return @"api/my/order_reply";
            break;
        case evaluation:return @"api/auth_api/user_comment_product";
            break;
        case evaluationlist:return @"api/auth_api/product_reply_list";
            break;
        case hotkeyword:return @"api/auth_api/hotkeyword";
            break;
        case goodsCategory:return @"api/auth_api/get_product_category";
            break;
        case mainfictitious:return @"api/index/fictitious";
            break;
        case maybe_love: return @"api/store/maybe_love";
            break;
        case get_coupon_user:return @"api/my/get_coupon_user";
            break;
        case seckill_index:return @"api/store/seckill_index";
            break;
        case set_cooperate:return @"api/auth_api/set_cooperate";
            break;
        default:return @"";
            break;
    }
}

@implementation NetWorkRequestDefine

@end
